# Generated by Django 5.0.1 on 2026-03-03 15:39

import file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=file.models.user_upload_path),
        ),
    ]
