# Generated by Django 6.0.1 on 2026-02-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
