# Generated by Django 6.0.1 on 2026-02-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('moderate', 'Can Moderate Post')]},
        ),
    ]
