# Generated by Django 5.2.12 on 2026-03-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
