# Generated by Django 5.0.1 on 2026-02-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='accounts.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_card', to='accounts.card')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
