# Generated by Django 5.0.1 on 2026-02-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_card_amount'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_card_transaction', to='accounts.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_card_transaction', to='accounts.card'),
        ),
    ]
