# Generated by Django 5.0.1 on 2026-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
