# Generated by Django 5.0.1 on 2026-02-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_card_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
