# Generated by Django 5.2.12 on 2026-06-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('dropoff_date', models.DateField(blank=True, null=True)),
                ('passenger_count', models.IntegerField(blank=True, null=True)),
                ('trip_distance', models.FloatField(db_index=True)),
                ('pickup_Longitude', models.FloatField(blank=True, null=True)),
                ('pickup_Latitude', models.FloatField(blank=True, null=True)),
                ('rate_code', models.CharField(blank=True, max_length=20, null=True)),
                ('store_and_fwd_flag', models.CharField(blank=True, max_length=2, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('fare_amount', models.CharField(blank=True, null=True)),
                ('surcharge', models.FloatField(blank=True, null=True)),
                ('mta_max', models.FloatField(blank=True, null=True)),
                ('trip_amount', models.FloatField(blank=True, null=True)),
                ('tools_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
